# Generated by Django 3.1.6 on 2021-02-09 21:40

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20201230_1805'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usercrypto',
            managers=[
                ('objects', authentication.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='usercrypto',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
