# Generated by Django 3.1.6 on 2021-02-16 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_wallet_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='test',
            new_name='alias',
        ),
    ]
