# Generated by Django 3.1.6 on 2021-02-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20210216_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='idWallet',
            field=models.CharField(max_length=32),
        ),
    ]
