# Generated by Django 3.1.6 on 2021-03-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20210216_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='idWallet',
            field=models.CharField(max_length=200),
        ),
    ]
