# Generated by Django 3.1.6 on 2021-03-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20210304_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercrypto',
            name='client',
            field=models.BooleanField(default=True),
        ),
    ]
