# Generated by Django 3.1.6 on 2021-03-30 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_usercrypto_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercrypto',
            name='client',
        ),
    ]
