version: '3.7'

services:
  app:
    build:
      context: .
    volumes:
      - static_data:/vol/web
    environment:
      #------DB configuration
      - DB_HOST=db
      - DB_NAME=crypto
      - DB_USER=postgres
      - DB_PASSWORD=crypto_money
      #------CORS configuration
      - CORS_ORIGIN_ALL:1
      - CORS_ALLOW=1
      #- CORS_ALLOWED_HOSTS:'http://localhost:3000'      
      #------Settings configuration
      - DEBUG=0
      - ALLOWED_HOSTS=*
      - SECRET_KEY=samplesecret123
      #-------JWT configuration
      - JWT_SECRET_KEY:JWT_SECRET_KEY
      

  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "80:8080"
    depends_on:
      - app

volumes:
  static_data: